; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define AppName "NMY Pointer"
#define AppId "E4CA0A60-4573-483B-8E56-884F20260908"
#define AppVerName "NMY Pointer V1.0.1"
#define AppExe "NmyStudio.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={#AppId}
AppName={#AppName}
AppVerName={#AppVerName}
AppPublisher=深圳市诺咪雅电子商务有限公司
AppPublisherURL=http://www.noomya.cn/
AppSupportURL=http://www.noomya.cn/
AppUpdatesURL=http://www.noomya.cn/
DefaultDirName={commonappdata}\NmyStudio
DefaultGroupName={#AppName}
AllowNoIcons=yes
UsePreviousAppDir=yes
OutputDir=D:\EasyPointer
OutputBaseFilename=NmyStudioInstaller-V1.0.1
SetupIconFile=Nmy.ico
Compression=lzma
SolidCompression=yes
Uninstallable=yes
CreateUninstallRegKey=yes
UninstallDisplayName={#AppVerName}
UninstallDisplayIcon={app}\Nmy.ico
PrivilegesRequired=admin
DisableDirPage=no
AlwaysShowDirOnReadyPage=yes

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

[Languages]
Name: "Chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: "English"; MessagesFile: "compiler:Default.isl"

[Files]
Source: bin\*; DestDir: {app}; Flags: recursesubdirs ignoreversion overwritereadonly

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons};

[Icons]
Name: {group}\{#AppName}; Filename: {app}\{#AppExe}
Name: {group}\{cm:UninstallProgram,{#AppName}}; Filename: {uninstallexe}; IconFilename: {app}\Nmy.ico
Name: {userdesktop}\{#AppName}; Filename: {app}\{#AppExe}; Tasks: desktopicon

[Run]
Filename: {app}\{#AppExe}; Description: {cm:LaunchProgram,{#AppName}}; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKCU; Subkey: Software\Microsoft\Windows\CurrentVersion\Run; ValueType: string; ValueName: NMYPointer; ValueData: {app}\{#AppExe}; Flags: uninsdeletevalue;
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\{#AppId}_is1"; Flags: uninsdeletekey

[Code]
var
  UninstallPath: String;
  ResultCode: Integer;

function RemoveOldVersion(): Boolean;
var
  UninstallString: String;
begin
  Result := True; 
  UninstallPath := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\{#AppId}_is1');

  if RegQueryStringValue(HKCU, UninstallPath, 'UninstallString', UninstallString) then
  begin
    Exec(UninstallString, '/SILENT', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    Exec(UninstallString, '/SILENT', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;
end;

// 入口函数：在初始化安装时调用
function InitializeSetup(): Boolean;
begin
  Result := True; 
  RemoveOldVersion();
end;